CREATE DATABASE IF NOT EXISTS steemo_db;

USE steemo_db;

CREATE TABLE IF NOT EXISTS usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  celular VARCHAR(20) NOT NULL,
  nivel ENUM('usuario','administrador') NOT NULL,
  senha VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS produtos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  titulo VARCHAR(100) NOT NULL,
  descricao TEXT NOT NULL,
  img VARCHAR(255) NOT NULL,
  valor DECIMAL(10,2) NOT NULL
);